---
# Variables in this file are automatically included into the role's context,
# and can be overridden by the active play.
# (Other files in this directory must be included via an `include_vars` task.)

# Which Jenkins release line to use: must be either 'long_term_support' or
# 'weekly'.
# FIXME: Default should probably be Long Term Support, but that would not be
# backwards compatible with earlier versions of this role.
jenkins_release_line: 'long_term_support'

# The directory that will be used as the home directory for the Jenkins service
# account. Cannot be modified, due to limitations in the Jenkins installers.
jenkins_home_default: '/var/lib/jenkins'

# The location that will be used to store the Jenkins configuration and data.
jenkins_home: "{{ jenkins_home_default }}"

# Jenkins doesn't (and shouldn't) run as root, so this must be over 1024.
jenkins_port: 8080

# The context path that Jenkins will be hosted at, e.g. '/foo' in
# 'http://localhost:8080/foo'. Leave as '' to host at root path.
jenkins_context_path: ''

# The external URL that users will use to access Jenkins. Gets set in the
# Jenkins config and used in emails, webhooks, etc.
# If this is left empty/None, the configuration will not be set and Jenkins
# will try to auto-discover this (which won't work correctly if it's proxied).
jenkins_url_external: ''

# The list of possible Jenkins admin users (and their security realm). At
# Jenkins startup, the current security realm will be checked, and the first
# user in this list that is found to match that security realm will have their
# SSH key set to allow SSH/CLI logins using the primary SSH key of the server's
# `jenkins` system user account. Any other Jenkins users with that SSH key set
# will have it removed, to prevent lookup conflicts.
# If you're using an alternative authorization system (i.e. security realm),
# this list will likely need to be modified to include the user ID of one of a
# valid user from that realm (unless it also happens to have an `admin`
# account).
jenkins_admin_users:
  - 'hudson.security.HudsonPrivateSecurityRealm:admin'

# The plugins that the Jenkins 2.0 setup wizard installs by default. Currently,
# the best place to find this list seems to be in the source, here:
# https://github.com/jenkinsci/jenkins/blob/master/core/src/main/resources/jenkins/install/platform-plugins.json
jenkins_plugins_recommended:
  - cloudbees-folder
  - antisamy-markup-formatter
  - build-timeout
  - credentials-binding
  - timestamper
  - ws-cleanup
  - ant
  - gradle
  - workflow-aggregator
  - github-branch-source
  - pipeline-github-lib
  - pipeline-stage-view
  - git
  - subversion
  - ssh-slaves
  - matrix-auth
  - pam-auth
  - ldap
  - email-ext
  - mailer

# The additional plugins that users of this role would like to be installed
# (must be overridden).
jenkins_plugins_extra: []

# Additional options that will be added to JAVA_ARGS
jenkins_java_args_extra: ''

##
# These should only be modified if custom/local mirrors of the YUM, APT, and/or
# plugins repositories are being used.
##

# The base URL of the custom YUM/APT repo to be used (the portion that's shared
# by the signing key and packages).
jenkins_packages_url_base: 'https://pkg.jenkins.io'

# Set to `true` to add a `proxy: _none_` setting for the YUM repo.
jenkins_packages_repo_yum_disable_proxy: false

