---

- name: Provision a Jenkins CI server
  hosts: all
  become: yes
  become_user: root
  remote_user: root
  vars:
    - update_cache: yes
    - jenkins_url_external: jenkins.sd2e.org
    - jenkins_home: '/jenkins/home'

  roles:
    - base
    - geerlingguy.docker
    - geerlingguy.java
    - karlmdavis.jenkins2
    - geerlingguy.nginx
    - infrastructure-agent-ansible
