---

- name: Provision a Jenkins CI server
  hosts: all
  become: yes
  become_user: root
  remote_user: vagrant
  vars:
    - update_cache: yes
    - jenkins_url_external: jenkins.local
    - jenkins_use_ldap: true

  roles:
    - base
    - { role: ansible-users.python, version: "2.7.14" }
    - { role: ansible-users.python, version: "3.6.4" }
    - { role: geerlingguy.nodejs, nodejs_version: "8.x" }
    - avahi
    - geerlingguy.docker
    - geerlingguy.java
    - karlmdavis.jenkins2
    - geerlingguy.nginx
