---

nginx_vhosts:
    - listen: "80 default"
      server_name: "{{ jenkins_url_external }}"
      access_log: "/var/log/nginx/jenkins.access.log"
      error_log: "/var/log/nginx/jenkins.error.log"
      proxy_buffers: "16 64k"
      proxy_buffer_size: "128k"
      extra_parameters: |
        location / {
            proxy_pass http://jenkins;
            proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
            proxy_redirect off;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto http;
        }

nginx_upstreams:
# - name: myapp1
#   strategy: "ip_hash" # "least_conn", etc.
#   keepalive: 16 # optional
#   servers: {
#     "srv1.example.com",
#     "srv2.example.com weight=3",
#     "srv3.example.com"
#   }
    - name: jenkins
      servers: {
          "127.0.0.1:8080"
      }
