---

- name: Install security updates
  yum:
      security=yes
      update_cache={{ update_cache }}
      name=*
      state=latest
  tags: packages
        packages.security

- name: Install EPEL-Release
  yum: name=epel-release update_cache={{ update_cache }} state=latest
  tags: packages

- name: Install IUS Repo
  yum: name=https://centos7.iuscommunity.org/ius-release.rpm
  tags: packages

- name: Install base packages
  yum: name={{ item }} update_cache={{ update_cache }} state=installed
  with_items:
    - "@Development tools"
    - ca-certificates
    - libsemanage-python
    - git
    - glances
    - jq
    - mailx
    - maven
    - raptor2
    - raptor2-devel
    - wget
  tags: packages

- name: Configure SELinux to allow httpd to connect to 127.0.0.1
  seboolean: name=httpd_can_network_connect state=yes persistent=yes
  when: ansible_selinux is defined and ansible_selinux.status == "enabled"
