---

jenkins_release_line: 'long_term_support'
jenkins_release_update: true
jenkins_admin_username: admin
jenkins_admin_password: admin
jenkins_admin_email: eferlanti@tacc.utexas.edu
jenkins_ldap_admin_user: eriksf
jenkins_ldap_server: 'ldaps://ldap.tacc.utexas.edu:636'
jenkins_ldap_root_dn: 'ou=people,dc=tacc,dc=utexas,dc=edu'

jenkins_plugins_extra:
  - ansible
  - batch-task
  - blueocean
  - build-pipeline-plugin
  - buildtriggerbadge
  - checkstyle
  - cobertura
  - copyartifact
  - deploy
  - disk-usage
  - external-monitor-job
  - favorite
  - ghprb
  - greenballs
  - groovy
  - icon-shim
  - jobConfigHistory
  - job-import-plugin
  - mailer
  - maven-plugin
  - metrics
  - monitoring
  - parameterized-trigger
  - pegdown-formatter
  - pubsub-light
  - run-condition
  - saferestart
  - shiningpanda
  - sse-gateway
  - slack
  - testng-plugin
  - variant
  - view-job-filters
  - warnings
